export const LANDSCAPE_ASPECT_RATIO='4/3'
  export const   LANDSCAPE_ASPECT_RATIO_PERCENTAGE='56.25%'
  export const PORTRAIT_ASPECT_RATIO='10/16'
  export const PORTRAIT_ASPECT_RATIO_PERCENTAGE='156.25%'
